# -*- coding: utf-8 -*-
"""exp3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CbBurjBAEq3PKSP7jAJvwaIxY0x7G5xG
"""

import torch.nn as nn
import matplotlib.pyplot as plt
import torchvision.transforms.v2 as T
import torchvision
import torch


transform_baseline = T.Compose([
    T.ToImage(), T.ToDtype(torch.float32), T.Normalize(
        mean=[0.4914, 0.4822, 0.4465], std=[0.2023, 0.1994, 0.2010])
])

transform_augmentation = T.Compose([
    T.ToImage(),
    T.RandomHorizontalFlip(),
    T.RandomCrop(32, padding=4),
    T.ToDtype(torch.float32),
    T.Normalize(mean=[0.4914, 0.4822, 0.4465], std=[0.2023, 0.1994, 0.2010])
])


def get_data_loaders(use_augmentation=True, val_size=5000, seed=42, num_workers=2):
    """
    Returns the training and validation data loaders for the CIFAR-10 dataset.

    Args:
        use_augmentation (bool): Whether to apply data augmentation to the training set.
        val_size (int): The number of samples to use for the validation set.
        seed (int): Random seed for reproducibility.
    """
    transform = transform_augmentation if use_augmentation else transform_baseline
    train_full = torchvision.datasets.CIFAR10(
        root='./data', train=True, download=True, transform=transform)
    val_full = torchvision.datasets.CIFAR10(
        root='./data', train=True, download=True, transform=transform)

    n_train = len(train_full) - val_size

    generator = torch.Generator().manual_seed(seed)
    prem = torch.randperm(len(train_full), generator=generator)

    train_dataset = torch.utils.data.Subset(train_full, prem[:n_train])
    val_dataset = torch.utils.data.Subset(
        val_full, prem[n_train:n_train + val_size])
    test_dataset = torchvision.datasets.CIFAR10(
        root='./data', train=False, download=True, transform=transform_baseline)

    trainloader = torch.utils.data.DataLoader(
        train_dataset, batch_size=128, shuffle=True, num_workers=num_workers)
    valloader = torch.utils.data.DataLoader(
        val_dataset, batch_size=128, shuffle=False, num_workers=num_workers)
    testloader = torch.utils.data.DataLoader(
        test_dataset, batch_size=128, shuffle=False, num_workers=num_workers)

    return trainloader, valloader, testloader


class CIFAR10Net(nn.Module):
    def __init__(self):
        super().__init__()

        self.stem = nn.Sequential(
            nn.Conv2d(3, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
        )
        self.stage1 = nn.Sequential(
            ResNetBlock(64),)
        self.pool1 = nn.MaxPool2d(2)

        self.expand2 = nn.Sequential(
            nn.Conv2d(64, 128, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(128),
            nn.ReLU(),)

        self.stage2 = nn.Sequential(
            ResNetBlock(128),)
        self.pool2 = nn.MaxPool2d(2)
        self.expand3 = nn.Sequential(
            nn.Conv2d(128, 256, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(256),
            nn.ReLU(),)

        self.stage3 = nn.Sequential(
            ResNetBlock(256),)
        self.head = nn.Sequential(
            nn.AdaptiveAvgPool2d((1)),
            nn.Flatten(),
            nn.Dropout(0.1),
            nn.Linear(256, 10))

    def forward(self, x):
        x = self.pool1(self.stage1(self.stem(x)))
        x = self.pool2(self.stage2(self.expand2(x)))
        x = self.stage3(self.expand3(x))
        x = self.head(x)
        return x

class ResNetBlock(nn.Module):
    def __init__(self, channels):
        super().__init__()
        self.conv1 = nn.Conv2d(channels, channels, kernel_size=3, padding=1,bias=False)
        self.bn1 = nn.BatchNorm2d(channels)
        self.conv2 = nn.Conv2d(channels, channels, kernel_size=3, padding=1,bias=False)
        self.bn2 = nn.BatchNorm2d(channels)
    def forward(self, x):
        out = self.conv1(x)
        out = self.bn1(out)
        out = nn.ReLU()(out)
        out = self.conv2(out)
        out = self.bn2(out)
        out += x  # Residual connection
        return torch.relu(out)



def train(num_epochs=200, patience=10, eval_every=1, val_size=5000, num_workers=2):

    print(
        f"Training for {num_epochs} epochs with patience {patience} and evaluation every {eval_every} epochs.")
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    trainloader, valloader, testloader = get_data_loaders(
        val_size=val_size, num_workers=num_workers)
    model = CIFAR10Net().to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9, weight_decay=5e-4)

    import copy
    best_val = 0
    best_model = copy.deepcopy(model.state_dict())
    patience_counter = 0

    for epoch in range(num_epochs):
        model.train()
        running_loss = 0.0
        for images, labels in trainloader:
            images = images.to(device)
            labels = labels.to(device)

            outputs = model(images)
            loss = criterion(outputs, labels)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            running_loss += loss.item()

        model.eval()
        correct = 0
        total = 0

        with torch.no_grad():
            for images, labels in valloader:
                images = images.to(device)
                labels = labels.to(device)
                outputs = model(images)
                _, predicted = torch.max(outputs.data, 1)
                total += labels.size(0)
                correct += predicted.eq(labels.data).sum().item()

        val_accuracy = 100 * correct / total
        if (epoch + 1) % eval_every == 0 or patience_counter >= patience:
            print(f"Epoch {epoch+1:3d} | Loss: {running_loss/len(trainloader):.4f} "
                  f"| Val: {val_accuracy:.1f}% | Best: {best_val:.1f}% (ep {best_epoch})")


        if val_accuracy > best_val:
            best_val = val_accuracy
            best_model = copy.deepcopy(model.state_dict())
            patience_counter = 0
        else:
            patience_counter += 1

    model.load_state_dict(best_model)

    return model, valloader, testloader, best_val


if __name__ == '__main__':
    model, valloader, testloader, best_val = train(
        num_epochs=50,
        patience=10,
        eval_every=5,
        val_size=5000,
        num_workers=2
    )